export const FETCH_PLANS = "FETCH_PLANS";
export const CREATE_PLAN_PERIOD = "CREATE_PLAN_PERIOD";
export const DELETE_PLAN_PERIOD = "DELETE_PLAN_PERIOD";
// export const FETCH_PLAN = "FETCH_PLAN";
// export const UPDATE_PLAN = "UPDATE_PLAN";
// export const DELETE_PLAN = "DELETE_PLAN";

export const FETCH_PERIODS = "FETCH_PERIODS";
export const CREATE_PERIOD = "CREATE_PERIOD";
export const DELETE_PERIOD = "DELETE_PERIOD";
