export const FETCH_PLANS = "FETCH_PLANS";
export const CREATE_PLAN = "CREATE_PLAN";
export const UPDATE_PLAN = "UPDATE_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";
// export const FETCH_PLAN = "FETCH_PLAN";

export const FETCH_PERIODS = "FETCH_PERIODS";
export const CREATE_PERIOD = "CREATE_PERIOD";
export const DELETE_PERIOD = "DELETE_PERIOD";
export const EDIT_PERIOD = "EDIT_PERIOD";

export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const FETCH_WORKEQUIPMENT = "FETCH_WORKEQUIPMENT";

export const FETCH_MATRIX = "FETCH_MATRIX";
